version: '3'
services:
  strat_trader:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/strat_trader
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - ./database/migration/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/1-ddl.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strat999
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/config/prometheus.yml
    volumes:
      - ./configs/prometheus.yml:/etc/config/prometheus.yml

  grafana:
    image: grafana/grafana
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards/
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"