// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package trades

import (
	"database/sql"
	"time"
)

type Country struct {
	ID   int64
	Name string
}

type Currency struct {
	ID             int64
	Code           string
	Name           string
	IsActive       bool
	IsBaseCurrency bool
}

type CurrencyRate struct {
	ID             int64
	CurrencyID     int32
	BaseCurrencyID int32
	Rate           string
	Ts             time.Time
}

type CurrencyUsed struct {
	ID         int64
	CountryID  int32
	CurrencyID int32
	DateFrom   time.Time
	DateTo     sql.NullTime
}

type CurrentInventory struct {
	ID       int64
	TraderID int32
	ItemID   int32
	Quantity string
}

type Item struct {
	ID         int64
	Code       string
	Name       string
	IsActive   bool
	CurrencyID int32
	Details    sql.NullString
}

type Offer struct {
	ID       int64
	TraderID int32
	ItemID   int32
	Quantity string
	Buy      bool
	Sell     bool
	Price    sql.NullString
	Ts       time.Time
	IsActive bool
}

type Price struct {
	ID         int64
	ItemID     int32
	CurrencyID int32
	Buy        string
	Sell       string
	Ts         time.Time
}

type Report struct {
	ID          int64
	TradingDate time.Time
	ItemID      int32
	CurrencyID  int32
	FirstPrice  sql.NullString
	LastPrice   sql.NullString
	MinPrice    sql.NullString
	MaxPrice    sql.NullString
	AvgPrice    sql.NullString
	TotalAmount sql.NullString
	Quantity    sql.NullString
}

type Trade struct {
	ID          int64
	ItemID      int32
	SellerID    sql.NullInt32
	BuyerID     int32
	Quantity    string
	UnitPrice   string
	Description string
	OfferID     int32
}

type Trader struct {
	ID                  int64
	FirstName           string
	LastName            string
	UserName            string
	Password            string
	Email               string
	ConfirmationCode    string
	TimeRegistered      time.Time
	TimeConfirmed       time.Time
	CountryID           sql.NullInt32
	PreferredCurrencyID sql.NullInt32
}
