// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package trades

import (
	"go.uber.org/zap"

	pb "strat_trader/api/trades/v1"
)

// NewService is a constructor of a pb.TradesServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(logger *zap.Logger, querier *Queries) pb.TradesServiceServer {
	return &Service{logger: logger, querier: querier}
}
